name: "Test"

on:
  push:
    paths-ignore:
    - 'docs/**'

# Our test suite should cover:
# - Compatibility with the most recent versions of Python, Wagtail and Django
# - at least one test run for older supported version of Python, Wagtail and Django
# - a test run against Django's git main branch (allowing failures)
# - a test run against Wagtail's git main branch (allowing failures)

# Current configuration:
# - python 3.9, django 3.2, wagtail 2.14 (+ linting and other checks)
# - python 3.8, django 3.1, wagtail 2.13
# - python 3.7, django 3.1, wagtail 2.12
# - python 3.6, django 3.1, wagtail 2.12

jobs:
  test-python:
    name: Test Python ðŸ
    env:
      DJANGO_SETTINGS_MODULE: wagtailpurge.tests.settings
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v2
      - name: âš™ï¸ Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: â¬‡ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "Django>=3.2,<3.3"
          pip install "Wagtail>=2.14,<2.15"
          pip install -e .[test]
      - name: âœ… Check for missing migrations
        run: django-admin makemigrations --check --noinput
      - name: ðŸª£ Collect static files
        run: django-admin collectstatic
      - name: ðŸ§ª Run tests
        run: pytest --junitxml=junit/test-results.xml --cov=wagtailpurge

  test-python-legacy:
    name: Test Python ðŸ with older dependencies
    env:
      DJANGO_SETTINGS_MODULE: wagtailpurge.tests.settings
    needs: test-python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: 3.8
            wagtail: "Wagtail>=2.13,<2.14"
            django: Django>=3.1,<3.2
          - python: 3.7
            wagtail: "Wagtail>=2.12,<2.13"
            django: Django>=3.1,<3.2
          - python: 3.6
            wagtail: "Wagtail>=2.12,<2.13"
            django: Django>=3.1,<3.2
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v2
      - name: âš™ï¸ Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: â¬‡ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "${{ matrix.django }}"
          pip install "${{ matrix.wagtail }}"
          pip install -e .[test]
      - name: ðŸª£ Collect static files
        run: django-admin collectstatic
      - name: ðŸ§ª Run tests
        run: pytest
